import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Vendor SDK is a snapshot of the audit-ready companion repo and is
      // auto-generated by Codama. Linting it surfaces issues that aren't
      // ours to fix here (they live upstream in Project-Tombola).
      "vendor/**",
    ],
  },
  {
    rules: {
      // `_foo` (or just `_`) by convention means "intentionally unused" —
      // common in for-await iterators where we don't need the value.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default eslintConfig;
